server:
  port: 8080
  servlet:
    context-path: /waterit/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/waterit
    username: waterit_admin
    password: Zaq123@!
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    drop-first: false


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 600000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

  prediction-model:
    url: http://107.152.36.118:8000/predict

logging:
  level:
    org.springframework.security: DEBUG
    springfox: DEBUG
  file:
    name: 'waterit.log'
    path: '/root'

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html